-----------------------------------------------Part-A-------------------------------------------------
--Create Department Table
CREATE TABLE Department (
 DepartmentID INT PRIMARY KEY,
 DepartmentName VARCHAR(100) NOT NULL UNIQUE
);
-- Create Designation Table
CREATE TABLE Designation (
 DesignationID INT PRIMARY KEY,
 DesignationName VARCHAR(100) NOT NULL UNIQUE
);
-- Create Person Table
CREATE TABLE Person (
 PersonID INT PRIMARY KEY IDENTITY(101,1),
 FirstName VARCHAR(100) NOT NULL,
 LastName VARCHAR(100) NOT NULL,
 Salary DECIMAL(8, 2) NOT NULL,
 JoiningDate DATETIME NOT NULL,
 DepartmentID INT NULL,
 DesignationID INT NULL,
 FOREIGN KEY (DepartmentID) REFERENCES Department(DepartmentID),
 FOREIGN KEY (DesignationID) REFERENCES Designation(DesignationID)
);


--1. Department, Designation & Person Table’s INSERT, UPDATE & DELETE Procedures.
--INSERT
CREATE OR ALTER PROCEDURE PR_DEPARTMENT_INSERT
		@DEPARTMENTID INT,
		@DEPARTMENTNAME VARCHAR(100)

AS
BEGIN
	INSERT INTO DEPARTMENT(
		DEPARTMENTID,
		DEPARTMENTNAME
		)
		VALUES
		(
		@DEPARTMENTID,
		@DEPARTMENTNAME
		)
END

CREATE OR ALTER PROCEDURE PR_DESIGNATION_INSERT
		@DESIGNATIONID INT,
		@DESIGNATIONNAME VARCHAR(100)

AS
BEGIN
	INSERT INTO DESIGNATION(
		DESIGNATIONID,
		DESIGNATIONNAME
		)
		VALUES
		(
		@DESIGNATIONID,
		@DESIGNATIONNAME
		)
END

CREATE OR ALTER PROCEDURE PR_PERSON_INSERT
		@FIRSTNAME VARCHAR(100),
		@LASTNAME VARCHAR(100),
		@SALARY DECIMAL(8,2),
		@JOININGDATE DATETIME,
		@DEPARTMENTID INT,
		@DESIGNATIONID INT
AS
BEGIN
	INSERT INTO PERSON(
		FIRSTNAME ,
		LASTNAME ,
		SALARY ,
		JOININGDATE,
		DEPARTMENTID,
		DESIGNATIONID 
		)
		VALUES
		(
		@FIRSTNAME,
		@LASTNAME,
		@SALARY,
		@JOININGDATE,
		@DEPARTMENTID,
		@DESIGNATIONID
		)
END

--EXEC QUERY


--UPDATE
CREATE PROCEDURE PR_DEPARTMENT_UPDATE
		@DEPARTMENTID INT,
		@DEPARTMENTNAME VARCHAR(100)
AS
BEGIN
	UPDATE DEPARTMENT
	SET DEPARTMENTNAME=@DEPARTMENTNAME
	WHERE DEPARTMENTID=@DEPARTMENTID;
END


CREATE PROCEDURE PR_DESIGNATION_UPDATE
		@DESIGNATIONID INT,
		@DESIGNATIONNAME VARCHAR(100)
AS
BEGIN
	UPDATE DESIGNATION
	SET DESIGNATIONNAME=@DESIGNATIONNAME
	WHERE DESIGNATIONID=@DESIGNATIONID;
END

CREATE PROCEDURE PR_PERSON_UPDATE
		@PERSONID INT,
		@FIRSTNAME VARCHAR(100),
		@LASTNAME VARCHAR(100),
		@SALARY DECIMAL(8,2),
		@JOININGDATE DATETIME,
		@DEPARTMENTID INT,
		@DESIGNATIONID INT
AS
BEGIN
	UPDATE PERSON
	SET
		FIRSTNAME=@FIRSTNAME,
		LASTNAME=@LASTNAME,
		SALARY=@SALARY,
		JOININGDATE=@JOININGDATE,
		DEPARTMENTID=@DEPARTMENTID,
		DESIGNATIONID=@DESIGNATIONID
	WHERE PERSONID=@PERSONID;
END